sonar.projectKey=thrini-thrive-mobile
sonar.projectName=ThriniThrive Mobile
sonar.sourceEncoding=UTF-8
sonar.sources=bayani-hub/src
sonar.tests=bayani-hub/tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/.expo/**,**/coverage/**,**/dist/**,hope-card/**/*,damayan/**/*
sonar.cpd.exclusions=hope-card/**/*,damayan/**/*,bayani-hub/**/*,**/*
