import { Campaign } from '@digdon/ui';

export const campaigns: Campaign[] = [
  {
    id: '1',
    title: 'Empower a New Generation of Scholars',
    description: 'Providing essential learning resources and mentorship to 500 children in underserved communities.',
    cover_image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD0sMTuVxihDdvfK60Wl_3jZ5JWA-eHi-Ztx8MkGH6VqP_dv2YRhjuysyxRjapRtNkYaJ2h1GvZDxVPXwZlG1o-io5pvFReMRf0gClwPSr8upaCg_jN7k19iyKNrmB0DMPHh-AfasatRiS656UGU4AvVP7_6REv3LXxPDZDstiwXxQMGc1BxqgAAZuYWrzJc502WjZtjAiVgz3V4PB5WuzyxBM9A-nYrcnTWskz9UpH8usz2Nb8YGb4R_J7ORPUPxrgNdFnQ42VPJ6s',
    target_amount: 25000,
    collected_amount: 20500,
    progress_pct: 82,
    category: 'Education',
    status: 'active',
    end_date: null,
  },
  {
    id: '2',
    title: 'Reforest the Ancient Valley',
    description: 'Protecting local biodiversity by planting 5,000 native tree species to restore the natural ecosystem.',
    cover_image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoBk7VFRjfzzycmsMZMyPANG24ZeZ_bb3akHt43xK1WCUmETA4yLD85l1Q-Kj1hfaGtAniHZ9Izmn_tv4GNoMCjmHWTuuBuiPKbRgIHeRXEOXQyo6sMsyrvD1Ex2Q_vYE4-MkueumVgkxZS2f2k8QzFTAjOFyi4JAlC6HdgaTzUlW4hpO9dB4twPW0DF3d1YPrDbN6bPbjCWYdUqm_Ac8B4xJeTjL9gWmW9pAuzsNSYWVcL4OtoIRm2VLH0fDt-BmFLhyZdNdhI9JF',
    target_amount: 10000,
    collected_amount: 4500,
    progress_pct: 45,
    category: 'Environment',
    status: 'active',
    end_date: null,
  },
  {
    id: '3',
    title: 'Rural Mobile Health Units',
    description: 'Providing critical medical checkups and vaccinations to isolated mountain villages.',
    cover_image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCeZozXMYf-7Hmye6OkJcB4kvjbtuClv-O4egJh0IcTw7zU2NjWcqBwb0NsPm9ma0qAI0ghh2DwSQ5PSCdsxCAdeIwAgeoFsgbW4QiEgI4Luwd20MmvfY2VLZtmtGUSDgvK5PS8ZbDZGAGXfNobr_aOiofViJ16FmJ6yppt7WWC_2GBtbGapcDbYWSxUJipDBrd_pRaZDaz_4nlTVZ7usjDkWmxtKJXC-td74glWSiuStBeW0E9ix6Df19j91STWXImtcQDOb_eF1No',
    target_amount: 25000,
    collected_amount: 17200,
    progress_pct: 68,
    category: 'Health',
    status: 'active',
    end_date: null,
  },
];
