sonar.projectKey=thrini-thrive-mobile
sonar.projectName=ThriniThrive Mobile
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/.expo/**,**/coverage/**,**/dist/**,app.config.ts,babel.config.js,eslint.config.ts,jest.config.ts,metro.config.js,index.ts
sonar.cpd.exclusions=**/*
